### ISSUE TITLE
[0.0.5] Error with in-memory files

### ISSUE THREAD

**Issue by spono** [stevenpawley/Rsagacmd#10]
Hi,
I'm testing your package and (luckily) a piece of your code as well.

```
library('Rsagacmd')
r = raster(file.path(out.folder,'raster', 'test.tif'))
crs(r) = projectCRS

# initiate a saga object
saga <- saga_gis()

pisr <- r %>%
  saga$pj_proj4$set_coordinate_reference_system(
    crs_method = 0,
    crs_proj4 = projectCRS ) %>%
  saga$ta_lighting$potential_incoming_solar_radiation(
    grd_direct = direct_radiation,
    grd_diffus = diffuse_radiation,
    grd_total = total_radiation,
    location = 1, 
    period = 2, 
    day = "2019-01-01", 
    day_stop = "2020-12-31",
    days_step = 5,
    hour_range = c(0, 24),
    hour_step = 0.5, 
    method = 2,
    lumped = 70
  )
```
The need for `pj_proj4` is due to the fact that it seems that SAGA doesn't read the CRS info from the file.

The use of pipes and "in-memory" objects is great but unfortunately, once I run it it gets into debug mode, and I can't get from where it comes from.

Any suggestion?

**Comment by stevenpawley** [comment]
Not all SAGA modules can be used with pipes. Based on the SAGA documentation, the 'Set Coordinate Reference System' http://www.saga-gis.org/saga_tool_doc/7.1.1/pj_proj4_0.html is accessible via the SAGA command line, but it doesn't provide an output of any kind. It only sets the coordinate reference system within SAGA, i.e. this particular module is only useful if you are using the GUI.

**Comment by stevenpawley** [comment]
Upon reflection, I’ll look to remove any of these strange tools that don’t have any outputs in a future version. Because the saga command line tools are also generated automatically by SAGA, there are probably a few other tools that are only useful when using the GUI

**Comment by spono** [comment]
> 
> 
> Not all SAGA modules can be used with pipes. Based on the SAGA documentation, the 'Set Coordinate Reference System' http://www.saga-gis.org/saga_tool_doc/7.1.1/pj_proj4_0.html is accessible via the SAGA command line, but it doesn't provide an output of any kind. It only sets the coordinate reference system within SAGA, i.e. this particular module is only useful if you are using the GUI.

ups...I missed that, I simply thought it was acting on the input file.
BTW, it didn't work with a single operation either, but maybe due to a lack of the CRS in the input file...I'm quite new to SAGA CLI and I don't find it that much explanatory, in case of errors.
Thanks for checking, though, I'll do some more tests in the meantime

**Comment by stevenpawley** [comment]
Fixed tools with no outputs being available in https://github.com/stevenpawley/Rsagacmd/commit/a382d8fc92d16d544cd66a56b3a883a2da41fc52
