### ISSUE TITLE
Mosaicking 

### ISSUE THREAD

**Issue by j-abele** [stevenpawley/Rsagacmd#11]
Hello Steven,

i have problems to execute the mosaicking function. If you pass a list with rasters the process seems to hang up.
Here I have described it in detail:

[https://stackoverflow.com/questions/64315765/using-mosaicking-with-rsagacmd-package-in-r](https://stackoverflow.com/questions/64315765/using-mosaicking-with-rsagacmd-package-in-r)

Maybe you have an idea?

**Comment by rhurlin** [comment]
Hi Jonas,

For me, the code from [1] runs without an error. 

Could you please give more info about the OS you are using, the R version and the version of SAGA GIS? Something like `devtools::session_info()` would be nice also.

Additionally, you could install Rsagacmd from github with newest changes via `devtools::install_github('stevenpawley/Rsagacmd')` and try your code again. I you give this a try, please report back ;)

Greetings,
Rainer

[1] https://stackoverflow.com/questions/64315765/using-mosaicking-with-rsagacmd-package-in-r

**Comment by j-abele** [comment]
Hey Rainer, 

thank you very much!

`<devtools::install_github('stevenpawley/Rsagacmd')>` was the solution. During the installation some packages were updated, so i guess that an outdated package caused the problem. Which one i unfortunately can't tell.

**Comment by rhurlin** [comment]
Nice to hear :)

I think you can close now the issue?
