### ISSUE TITLE
Questions about the saga object structure

### ISSUE THREAD

**Issue by Nowosad** [stevenpawley/Rsagacmd#21]
Hi again @stevenpawley -- currently I am working on a section about bridging SAGA GIS with R for the section edition of Geocomputation with R (https://geocompr.robinlovelace.net/gis.html#saga). It made me think about a few aspects of **Rsagacmd**:

- Each tool prints a tibble with parameters names, arguments, etc. However, is it possible to actually get this tibble? I am asking because it is often impossible to see complete arguments names or descriptions with this approach...

``` r
library(terra)
#> terra 1.5.24
library(Rsagacmd)
saga = saga_gis(backend = "terra")
obis = saga$imagery$object_based_image_segmentation
obis
#> Help for library = imagery; tool = object_based_image_segmentation:
#> Author: nO.Conrad (c) 2014 
#> Description: This tool chain combines a number of tools for an easy derivation of geo-objects as polygons and is typically applied to satellite imagery. Segmentation is done using a 'Seeded Region Growing Algorithm'. Optionally the resulting polygons can be grouped by an unsupervised classification (k-means cluster analysis), which is performed on the basis of zonal feature grid statistics for each polygon. 
#> 
#> # A tibble: 13 × 7
#>    parameter        type  argument identifier description default available_opts
#>    <chr>            <chr> <chr>    <chr>      <chr>         <dbl> <chr>         
#>  1 Features         Grid… features FEATURES   <NA>             NA <NA>          
#>  2 Segments         Shap… objects  OBJECTS    <NA>             NA <NA>          
#>  3 Normalize        Bool… normali… NORMALIZE  <NA>              0 <NA>          
#>  4 Band Width for … Floa… seeds_b… SEEDS_BAN… Increase b…       2 <NA>          
#>  5 Neighbourhood    Choi… rga_nei… RGA_NEIGH… <NA>              0 [0] 4 (Neuman…
#>  6 Distance         Choi… rga_met… RGA_METHOD <NA>              0 [0] feature s…
#>  7 Variance in Fea… Floa… rga_sig… RGA_SIG_1  <NA>              1 [0] Minimum: …
#>  8 Variance in Pos… Floa… rga_sig… RGA_SIG_2  <NA>              1 [0] Minimum: …
#>  9 Similarity Thre… Floa… rga_sim… RGA_SIMIL… <NA>              0 [0] Minimum: …
#> 10 Generalization   Inte… majorit… MAJORITY_… Applies a …       1 <NA>          
#> 11 Post-Processing  Choi… postpro… POSTPROCE… Number of …       0 [0] none; [1]…
#> 12 Number of Clust… Inte… ncluster NCLUSTER   Number of …      12 <NA>          
#> 13 Split Clusters   Bool… split_c… SPLIT_CLU… Number of …       1 <NA>
```

- Have you considered (would it be possible) to add a link to the documentation on the SAGA GIS website for each tool?

**Comment by stevenpawley** [comment]
Hi! You can get the actual tibble by using the 'tidy' method on the tool, which maybe is a bit strange because it is being used on a function as the object, rather than some other list-like object. However, I was going to extend this method to the library level, and the saga object itself to get tibbles of information about each tool in a library, and the libraries themselves.

**Comment by stevenpawley** [comment]
That's a great suggestion about the url link. I'll see if that is possible.

**Comment by Nowosad** [comment]
Hi @stevenpawley,
thanks for the reply.

Have you considered a different name than `tidy()`. It seems very generic... How about `saga_tidy()` or similar?

(I also plan to open an issue or two more -- l hope they could be useful for the package development)

**Comment by stevenpawley** [comment]
`tidy()` was used because it is already a generic in the tidyverse for tuning an object into a tibble, so it seemed reasonable, albeit it is mostly used in the **recipes** package. Alternatives like `summary` tend to be used for statistical summaries or fitted models rather than returning a data.frame/tibble

**Comment by Nowosad** [comment]
Thanks for the explanation -- I was not aware of `tidy()`.
