### ISSUE TITLE
Topology issue with Rsagacmd output

### ISSUE THREAD

**Issue by Nowosad** [stevenpawley/Rsagacmd#22]
I am unable (yet) to determine if the issue below is caused by Rsagacmd handling of the output or SAGA GIS itself... It seems that the clustering output has broken topology (causes GEOS errors).

``` r
library(sf)
#> Linking to GEOS 3.9.2, GDAL 3.3.3, PROJ 8.2.1; sf_use_s2() is TRUE
library(terra)
#> terra 1.5.26
library(Rsagacmd)
saga = saga_gis()
ndvi = rast(system.file("raster/ndvi.tif", package = "spDataLarge"))
plot(ndvi)
```

![](https://i.imgur.com/px8E8qY.png)

``` r
obis = saga$imagery$object_based_image_segmentation

output = obis(ndvi, ncluster = 12, postprocessing = 1)
plot(output)
#> Error in CPL_geos_is_empty(st_geometry(x)): Evaluation error: IllegalArgumentException: Points of LinearRing do not form a closed linestring.
```

``` r
st_is_valid(output)
#>  [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
#> [26] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
#> [51] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
#> [76] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by stevenpawley** [comment]
It looks like this is related to the tool itself. If I run `output = st_cast(output, "POLYGON")` then the segmentation can be plotted although some geometries have been lost. The `object_based_image_segmentation` is a toolchain rather than one of the core SAGA-GIS tools that internally runs the seeded region growing -> imagery_segmentation -> majority_filter -> shapes_to_grid and finally cluster analysis.

**Comment by stevenpawley** [comment]
I should have added that some versions of SAGA appear to have other side effects with geometries, i.e. outputting all geometries as 3D even when the inputs were 2D, which can lead to warnings or frequent use of `st_zm()`.

**Comment by Nowosad** [comment]
Thanks for the explanation, @stevenpawley.
