### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [stevenpawley/Rsagacmd#23]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by stevenpawley** [comment]
Thanks Roger,

I'll be submitting a new version to CRAN this week without the **raster** dependency.

**Comment by rsbivand** [comment]
Do you have a new timeline for releasing a version without dependencies on retiring spatial infrastructure packages? Please fix best by June, latest October 2023.

**Comment by stevenpawley** [comment]
Thanks for the reminder - I have a branch that is raster and rgdal free, will be submitting to CRAN after a little more testing

**Comment by rsbivand** [comment]
Great, thanks for your co-operation! See also https://r-spatial.org/r/2023/04/10/evolution3.html foor tips on testing.

**Comment by stevenpawley** [comment]
Submitted to CRAN with the dependencies to the retiring packages removed
