### ISSUE TITLE
Error in if (params[[n]]$feature == table_features) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by evhersh** [stevenpawley/Rsagacmd#28]
Hello,

I found my way to this tool after trying to use RSAGA and having issues with installation on MacOS. I'm running into an error already trying out the example code on Github: 

```
library(Rsagacmd)
> saga <- saga_gis(raster_backend = "terra")
Multiple installations of SAGA-GIS were found at:
/Applications/SAGA.app/Contents/MacOS/saga_cmd
/Applications/QGIS.app/Contents/MacOS/bin/saga_cmd
Choosing newest version. Manually specify the location when calling saga_gis() to use an older version
> srtm <- read_srtm()
> srtm
class       : SpatRaster 
dimensions  : 400, 400, 1  (nrow, ncol, nlyr)
resolution  : 100, 100  (x, y)
extent      : 310009.9, 350009.9, 5879989, 5919989  (xmin, xmax, ymin, ymax)
coord. ref. : NAD83(CSRS) / Alberta 10-TM (Forest) (EPSG:3402) 
source      : srtm.tif 
name        :   N53W118 
min value   :  951.8326 
max value   : 2580.7278 
> saga$ta_morphometry$mass_balance_index(dem = srtm)
Error in if (params[[n]]$feature == table_features) { : 
  missing value where TRUE/FALSE needed
```

I have the latest versions of terra, SAGA GIS, and Rsagacmd installed. Please let me know if I'm missing something obvious.

**Comment by stevenpawley** [comment]
Hello, thanks for reporting, I was able to reproduce this on SAGA 9.2, which made a slight change that caused Rsagacmd to be unable to recognize the output types of some tools. This should be fixed now, let me know if there are any problems. I'll submit a new version to CRAN over the next few days. In the meanwhile, you can just install from GitHub with:

`remotes::install_github("stevenpawley/Rsagacmd")`

**Comment by evhersh** [comment]
Thanks Steven! Everything seems to be running well now. Thanks for the awesome package!
