### ISSUE TITLE
Initialize a saga object error for a stand-alone version of SAGA-GIS  in win11

### ISSUE THREAD

**Issue by SpatLyu** [stevenpawley/Rsagacmd#34]
I have istalled the standalone version SAGA-GIS in win11, when i try to initialize a saga object, I got the following error:

``` r
library(Rsagacmd)
saga = saga_gis(saga_bin = 'd:/application/saga/saga_cmd.exe')
#> Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version): invalid non-character version specification 'x' (type: double)
```

<sup>Created on 2024-08-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I'm using the saga_9.5.1_x64 version, and the session of r:
``` r
sessionInfo()
#> R version 4.4.1 (2024-06-14 ucrt)
#> Platform: x86_64-w64-mingw32/x64
#> Running under: Windows 11 x64 (build 22631)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=Chinese (Simplified)_China.utf8 
#> [2] LC_CTYPE=Chinese (Simplified)_China.utf8   
#> [3] LC_MONETARY=Chinese (Simplified)_China.utf8
#> [4] LC_NUMERIC=C                               
#> [5] LC_TIME=Chinese (Simplified)_China.utf8    
#> 
#> time zone: Asia/Shanghai
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.36     fastmap_1.2.0     xfun_0.46         glue_1.7.0       
#>  [5] knitr_1.48        htmltools_0.5.8.1 rmarkdown_2.27    lifecycle_1.0.4  
#>  [9] cli_3.6.3         reprex_2.1.1      withr_3.0.1       compiler_4.4.1   
#> [13] rstudioapi_0.16.0 tools_4.4.1       evaluate_0.24.0   yaml_2.3.10      
#> [17] rlang_1.1.4       fs_1.6.4
```

<sup>Created on 2024-08-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by SpatLyu** [comment]
The development version in github works well:

``` r
devtools::install_github("stevenpawley/Rsagacmd")
saga = Rsagacmd::saga_gis(saga_bin = 'd:/application/saga/saga_cmd.exe')
```

<sup>Created on 2024-08-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Additionally, I have a suggestion to add options set in R for the saga_bin parameter in the `saga_gis()` function, using either `options()` or `Sys.setenv()`. For example, you could use something like `options(saga_cmd = 'path/to/saga_cmd')`. This would eliminate the need to update the PATH environment variable each time a new version of SAGA GIS is installed on Windows platforms, and then restart for it to take effect (the default binary version comes with a version number after unzipping, meaning that an update requires synchronizing the environment variable). I guess many people don't like manually setting the PATH variable on Windows, haha.

**Comment by SpatLyu** [comment]
I have submitted a PR under this topic for your review, @stevenpawley

**Comment by stevenpawley** [comment]
Thanks for reporting this - it was fixed recently in the development version and I need to submit back to CRAN. Thanks also for the PR for the `options()` idea - that's great!
