### ISSUE TITLE
Error in file(con, "rb") : cannot open the connection

### ISSUE THREAD

**Issue by amsantac** [stevenpawley/Rsagacmd#4]
Hi. Very promising package,

When trying to run sagaGIS() from Rsagacmd v. 0.1.0 I get the following on Windows and on Linux:

```
> library(Rsagacmd)
> saga = sagaGIS()
Error in file(con, "rb") : cannot open the connection
In addition: Warning messages:
1: running command '"saga_cmd" --create-config=C:\Users\AL61EE~1\AppData\Local\Temp\Rtmp2VMcNd\file2f707da5f44.ini' had status 1 
2: In file(con, "rb") :
  cannot open file 'C:\Users\AL61EE~1\AppData\Local\Temp\Rtmp2VMcNd\file2f707da5f44.ini': No such file or directory
```

I get the same error when using OSGeo4W64 SAGA versions:

```
> saga = sagaGIS('C:/OSGeo4W64/apps/saga/saga_cmd.exe')
> saga = sagaGIS('C:/OSGeo4W64/apps/saga-ltr/saga_cmd.exe')
```

When using standalone SAGA version I get: 

```
> saga = sagaGIS('C:/saga-6.3.0_x64/saga_cmd.exe')
Error in R6Class("sagaGIS", private = list(senv = NULL), public = list(gp = list(),  : 
  could not find function "R6Class"
```

On Linux (OSGeo-live 10.5) I get:

```
> library("Rsagacmd", lib.loc="/usr/local/lib/R/site-library")
> saga <- sagaGIS()
Error: select a library
Error in file(con, "rb") : cannot open the connection
In addition: Warning messages:
1: running command ''saga_cmd' --create-config=/tmp/RtmpnCpEN7/file8f2bc9dbc7.ini' had status 1 
2: In file(con, "rb") :
  cannot open file '/tmp/RtmpnCpEN7/file8f2bc9dbc7.ini': No such file or directory
```

The package was running well with initSAGA() in previous version.

Thanks for your work and for your help,

Ali

Session info on Windows:

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rsagacmd_0.1.0 learnr_0.9.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15    XML_3.98-1.10   withr_2.1.1     digest_0.6.15   rprojroot_1.3-2 mime_0.5        R6_2.2.2        xtable_1.8-2   
 [9] jsonlite_1.5    backports_1.1.2 magrittr_1.5    evaluate_0.10.1 stringi_1.1.6   rmarkdown_1.8   tools_3.4.3     stringr_1.3.0  
[17] htmlwidgets_1.0 markdown_0.8    shiny_1.0.5     httpuv_1.3.5    yaml_2.1.16     compiler_3.4.3  htmltools_0.3.6 knitr_1.19 
```

**Comment by stevenpawley** [comment]
Hi Ali,

Apologies I made some major changes recently to make the package a less 'hacky' and something went wrong with my GitHub repo. It seems to be working for me now, please test and let me know if there are any problems.

Steve

**Comment by stevenpawley** [comment]
As a follow-up, two errors occurred here. One was related to a problem with the new version's package installation, which hopefully should be fixed if you are using windows and SAGA 6.3.0.

I will have to introduce a check to the SAGA-GIS version for second problem related to the 'running command ''saga_cmd' --create-config='. This is because I added an option to use disk caching, and create a custom saga_cmd configuration file to active this. It appears that the '--create-config' flag was only added in a recent version of SAGA-GIS, so it also doesn't work on my machine if I use an older SAGA version including the OSGEO version which is 2.3.1.

**Comment by amsantac** [comment]
Hi Steven,

Thanks for your quick reply,

It seems to be working well now in my pc on Windows with both the OSGeo4W and the standalone version. Only a warning is shown for the latter:

```
library(Rsagacmd)
saga = sagaGIS('C:/saga-6.3.0_x64/saga_cmd.exe')
Warning message:
Problem parsing SAGA-GIS library = imagery_tools; and tool = Universal_Image_Quality_Index
```

Thanks a lot for your help. Keep up the good work!

Ali

**Comment by stevenpawley** [comment]
Thanks Ali,

Yes that warning is because that particular SAGA-GIS tool has two identically-named arguments, so it cannot be used as a function. Will get in touch with the SAGA developers to take a look at it.

Steve
